databases:
  - name: db
    plan: free
    databaseName: db
    user: api

services:
  - type: web
    name: api
    plan: free
    env: docker
    dockerfilePath: Dockerfile.render
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://drone-api.onrender.com"
      - key: MQTT_BROKER_HOST
        sync: false
      - key: MQTT_BROKER_PORT
        sync: false
      - key: MQTT_BROKER_USERNAME
        sync: false
      - key: MQTT_BROKER_PASSWORD
        sync: false
    healthCheckPath: /api/schema/swagger-ui/