# Generated by Django 5.2.3 on 2025-06-20 18:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField()),
                ('last_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('last_height', models.FloatField()),
                ('last_speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OSDData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.FloatField()),
                ('horizontal_speed', models.FloatField()),
                ('raw_data', models.JSONField()),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osd_data', to='drones.drone')),
            ],
        ),
    ]
