# Generated by Django 5.2.3 on 2025-06-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_rename_osddata_dronedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='dangerous_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='is_dangerous',
            field=models.BooleanField(default=False),
        ),
    ]
