# Generated by Django 5.2.3 on 2025-06-22 10:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_drone_dangerous_reason_drone_is_dangerous'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoFlyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4236)),
            ],
        ),
    ]
