# Generated by Django 5.2.3 on 2025-06-22 11:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_noflyzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noflyzone',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
    ]
